sudo: required
services:
  - docker
language: node_js
node_js:
  - 9
cache:
  directories:
    - node_modules

aliases:
  before_deploy: &before_deploy
    - docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
    - docker build --no-cache --tag registry.heroku.com/$APP/web .
  deploy: &deploy
    provider: script
    script:
      - docker push registry.heroku.com/$APP/web

jobs:
  include:
  - stage: Test (unit)
    script:
      - npm run lint
      - npm run stylelint
      - npm run test

  - stage: Deploy (test)
    if: tag IS blank
    env:
      - APP=shri-git-store-test
    before_deploy:
      <<: *before_deploy
    deploy:
      <<: *deploy
      app: shri-git-store-test
      on:
        all_branches: true

  - stage: Deploy (development)
    if: tag IS blank
    env:
      - APP=shri-git-store-master
    before_deploy:
      <<: *before_deploy
    deploy:
      <<: *deploy
      app: shri-git-store-master
      on:
        branch: master

  - stage: Deploy (production)
    if: tag IS present
    env:
      - APP=shri-git-store-production
    before_deploy:
      <<: *before_deploy
    deploy:
      <<: *deploy
      app: shri-git-store-production
      on:
        tags: true
