sudo: false
language: node_js

node_js:
- 9
- 8

script:
- npm run lint
- npm run stylelint
- npm run test
- npm run build

aliases:
  deploy:
    provider: heroku
    api_key: &1
      secure: W8TPmyDhtlUVSrST7ocspQghYz4IF6Z9SipbBxVv4nKf8IOu0VXdPqAHVfkuG6G+rRua1kDgW5KluFFZg4dQPf6RLZi5LanlNsmsnY25hgl3RWGGInU7j1tEE9aF+G58qmZ+NxviSt6/ccqcEVMJJBC/6JymE5Ev+13IWVmCjFsU94UVDgDH5Q5yrELv+gqqqkh3WOAsmpbB6umZWIOEnpq5ibPE/cwlBq3qKSOK86TR2exUQjNmQUudKQCSLG0gwFC4cPnSb9cxauFv2kuyBC4T0xvb2sHO9bkaiHP3XNjH/kSrY5D+0NVs08MsjSK5xipMQ9955npTWpi2bMD7mluii/sfXjma50a7O0uAjaiN1PwQsdmBXq5aOyS3TlUAU4c1/qjSR7gL0r0xrO0ModVDzSzXpDZ8Yl0J5K+F1WgnGKGxr9KYLjsvnUhPLJ1UxUA8oYCiIheP6t7bPeBIGwselW57sKlujEExZYRrJfRPHKv0qid92JF7QpkKC04mnl44LUSY5cBrBgaogeNh295xgUfo1EHm6Hc2gMsGgmyVFVxQCjyEupyLQmm9cpPp1PPdPgssxnBXSZyCw1R8WQcATc0sZFcWJX0rrcSg6sHLqNXFAeOWXP2LlytnuEQ1AO6lw0z22fDKrUN0kpQxM1aM4WSXKjqUzEK34NAhj3U=
    skip_cleanup: true

jobs:
  include:
  - stage: Deploy (development)
    if: tag IS blank
    script:
    - npm run build
    deploy:
      provider: heroku
      api_key: *1
      skip_cleanup: true
      app: shri-git-store-master
  - stage: Deploy (production)
    if: tag IS present
    script:
    - npm run build
    deploy:
      provider: heroku
      api_key: *1
      skip_cleanup: true
      app: shri-git-store-production
      on:
        tags: true
